disabled_rules: # rule identifiers to exclude from running
  # - closing_brace
  # - colon
  # - comma
  # - control_statement
  # - custom_rules
  # - cyclomatic_complexity
  # - file_length
  # - force_cast
  # - force_try
  # - function_body_length
  # - function_parameter_count
  # - implicit_getter
  # - leading_whitespace
  # - legacy_cggeometry_functions
  # - legacy_constant
  # - legacy_constructor
  # - legacy_nsgeometry_functions
  # - line_length
  # - mark
  # - nesting
  # - opening_brace
  # - operator_whitespace
  # - private_unit_test
  # - return_arrow_whitespace
  # - statement_position
  # - syntactic_sugar
  # - todo
  # - trailing_comma
  # - trailing_newline
  # - trailing_semicolon
  - trailing_whitespace
  # - type_body_length
  # - type_name
  # - valid_docs
  # - valid_ibinspectable
  # - variable_name
  # - vertical_whitespace
  # - weak_delegate
opt_in_rules: # some rules are only opt-in
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - explicit_init
  - force_unwrapping
  - missing_docs
  - nimble_operator
  - overridden_super_call
  - private_outlet
  - redundant_nil_coalescing
  - switch_case_on_newline
included: # paths to include during linting. `--path` is ignored if present.
  #- App
  #- AppTests
  #- AppUITests
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

# Custom Configuration

line_length:
  warning: 150
  error: 175

variable_name:
  excluded:
    - ID
    - id
